### ISSUE TITLE
Mejoras para los diseños de las cartas

### ISSUE THREAD

**Issue by marioortizmanero** [UNIZAR-30226-2021-07/assets#17]
Cambiar las cartas lleva mucho tiempo porque es un proceso manual, así que si tenéis alguna sugerencia ponedlas aquí y lo haré cuando quede poco para la siguiente entrega ya. Así evito hacerlo varias veces.

**Comment by marioortizmanero** [comment]
Los órganos en sus cartas deberían ser más opacas y posiblemente tener bordes negros.

**Comment by marioortizmanero** [comment]
Las cartas serían más fáciles de distinguir sin el fondo del patrón de bacterias. Habría que quitarlo y decidir si es mejor manteniendo el degradado o con color plano. Hago una comparación para que deis opiniones

a. ![image](https://user-images.githubusercontent.com/25647296/115956680-7ebe9600-a4fe-11eb-9ad2-c19015577f04.png)

b. ![image](https://user-images.githubusercontent.com/25647296/115956674-78301e80-a4fe-11eb-8da6-c4931a1ccddd.png)

c. ![image](https://user-images.githubusercontent.com/25647296/115956699-95fd8380-a4fe-11eb-8ef1-e050e1f34296.png)

**Comment by jmarindiez** [comment]
Yo la primera la descartaba. Las otras dos estan bien, aunque quizas me quedaba con la ultima.

**Comment by Tomenos18** [comment]
Cuando cambieis las cartas, recordad porfa ponerlas en formato png también porfis

**Comment by jmarindiez** [comment]
`cuerpo_estomago` esta mal. Esta como medicina cuando es organo

**Comment by xzebra** [comment]
> Yo la primera la descartaba. Las otras dos estan bien, aunque quizas me quedaba con la ultima.

coincido con este tio en todo lo que dice

**Comment by xzebra** [comment]
Es necesario que los svg se compriman, porque ahora mismo pesan 5 MB y para la carga de la web es muy pesado

**Comment by FCanfran** [comment]
La c la mejor para mi

**Comment by marioortizmanero** [comment]
@Tomenos18 me pidió también exportar un marco con la carta con mayor anchura de borde, para poderlo poner cuando el usuario no tiene una carta.
